-- ===================================================================
-- 003-review-quiz.sql
--
-- 復習クイズの原稿を持つ列（docs/plan-quiz.md）。
--
--   { "question": "…", "choices": ["…","…","…"], "answer": 2 }
--
-- NULL 許可 ── クイズの無い日はそれで正常で、配信側が
-- quiz IS NOT NULL で除ける。原稿が無ければ本編だけが届く
-- （運勢 fortune-lines.json と同じ態度）。
--
-- answer は 0 始まりの添字。**サーバーだけが読む。**
-- postback の data に載せてはいけない ── data は利用者の端末を
-- 経由して戻る文字列で、押す前に書き換えれば必ず正解になる
-- （lib/handlers/postback.mjs の冒頭）。
--
-- 節目クイズ（30/50/75、action=quiz）もこの列を読む。
-- 「正答の置き場所は入稿設計で決まる」と保留されていた場所が
-- ここに決まった ── 別の列を作ると、同じ日の復習と節目で
-- 違う問題・違う正答を持ててしまう。
ALTER TABLE content_templates ADD COLUMN quiz JSON NULL;
